### PR TITLE
Functional way to FingersCrossedProcessor

### PR DESCRIPTION
**Pull request by sergiors**

### CODE REVIEW

**Comment by sergiors** [comment]
@frankdejonge any opinion?

**Comment by frankdejonge** [comment]
@sergiors Hi, I had it this way initially, but exception in array_reduce are converted to fatal exceptions so in order to be usable I had to use a foreach loop :(

**Comment by sergiors** [comment]
What do you think to use `try/catch` to convert the result?

**Comment by sergiors** [comment]
And change  `call_user_func($stage, $payload)` to `$stage($payload)`?

**Comment by frankdejonge** [comment]
I don't want to enforce people to have to deal with exception internally just because of the use of an `array_reduce`.

**Comment by frankdejonge** [comment]
Just to be clear, there's nothing "better" about having a array_reduce, the code does exactly the same, in fact it USED to be an array_reduce but with pain in my heart I replaced it with a foreach loop because of the fatal errors.

**Comment by sergiors** [comment]
I got it

**Pull request closed without merging**
