### PR TITLE
[Discussion] Renamed Operation to Stage

### PR DESCRIPTION
**Pull request by frankdejonge**
In the pattern definition the operations are called stages. Implementations in other languages use this terminology as well. I think this, and the benefit of clarity can justify a rename.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@kayladnls I'd like your opinion here, I think it's pretty clear and the way to go.

**Comment by frankdejonge** [comment]
Reference: http://www.cise.ufl.edu/research/ParallelPatterns/PatternLanguage/AlgorithmStructure/Pipeline.htm

**Comment by reinink** [comment]
I think I like stage better. Many stages make up an operation (the pipeline).

**Comment by greydnls** [comment]
The way I read it, a pipeline has many stages, stages have many operations. 

In either case, I think the rename is good.

**Comment by frankdejonge** [comment]
@reinink @kayladnls thanks for the feedback people, I'll go ahead and merge this. Will probably release something soon. Starting off with a 0.1.0 sanity check. Tried releasing a 1.0.0-beta, but that seemed premature. Not because of the code, because it's barely any, but because of the implications of settings the interfaces in stone.

**Pull request merged**
