### PR TITLE
Test on new PHP

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Review by shadowhand — APPROVED** [review]

**Review by jdreesen — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Why have you guys approved this when it doesn't work? Travis is failing on PHP 7.4.

**Comment by GrahamCampbell** [comment]
Ok, now this should work. :)

**Comment by shadowhand** [comment]
@GrahamCampbell in my case, approving means "I support this approach." Tests failing is a different issue.

**Review by shadowhand — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Ready for merge, I think? ;)

**Comment by GrahamCampbell** [comment]
Friendly ping @frankdejonge. :)

**Pull request closed without merging**
