### PR TITLE
Use callable instead of StageInterface::process

### PR DESCRIPTION
**Pull request by frankdejonge**
In order to be more compatible with other packages, like tactician, the StageInterface was problematic and required additional wrapping to play nice with others. Stages, in concept, are already pretty close to callable ... things. The StageInterface is still in place, but now enforces the `__invokable` methods with a single method parameter signature. This is, not coincidentally, is _exactly_ the signature of the "old" `StageInterface::process`.

So, in short. Let's make this package more open to work with others.

_UPGRADE!_

So simple. Every implementation of the StageInterface should replace the method name `process` with `__invoke`. Also, the CallableStage is now not needed anymore and can be unwrapped, so those are quite easy to port over. So, not much change, many benefits.

_EXAMPLES!_

``` php
// BEFORE
$pipeline->pipe(CallableStage::forCallable(function ($payload) {
    return $payload;
}))->process($payload);

// After
$pipeline->pipe(function ($payload) {
    return $payload;
})->process($payload);
```

Stages:

``` php
// BEFORE
class MyStage implements StageInterface
{
    public function process($payload)
    {
        return $payload;
     }
}

// AFTER
class MyStage implements StageInterface
{
    public function __invoke($payload)
    {
        return $payload;
     }
}
```

The rest of the API hasn't changed.

_THOUGHTS!_

Thoughts? .. /cc @rosstuck

### CODE REVIEW

**Comment by rosstuck** [comment]
Have to dig in more, but a hearty :+1: at a glance.

I might go a step further and just replace `StageInterface` with the `callable` typehint. We went down the marker interface road with Tactician before and it offered nothing, really.

**Comment by frankdejonge** [comment]
@rosstuck well actually... ;) it already does that, the interface is merely there for classbased stuff to clarify intent of the class rather than being hinted on.

**Comment by frankdejonge** [comment]
@nyamsprod any feedback on this?

**Comment by nyamsprod** [comment]
a big +1 from me. In the code I see that the Pipeline class still exposes the process method as public ... will the method be deprecated or its a "leftover" from the previous implementation ?

**Comment by frankdejonge** [comment]
@nyamsprod the process method is there to still allow a nice API, forcing people to treat is as a callable is not very nice. Also, the process method there is the common use-case, where in the stages only the invoke method is the common use-case.

**Comment by nyamsprod** [comment]
@frankdejonge thanks for the clarification. I'm eager to require the v1.0.0 release :)

**Comment by SebSept** [comment]
To me, for my usage, without this feature, create a class foreach stage is too much verbosity. I hope it can be merged.

**Comment by SebSept** [comment]
:+1:

**Pull request merged**
